### ISSUE TITLE
Downloading Looking annotation link error

### ISSUE THREAD

**Issue by sunggukcha** [vita-epfl/looking#1]
Hello there, thanks for your great efforts and sharing great results. 

I am interested in your works and trying to do some experiments with your repo. 
Following your guidelines, downloading LOOK annotation file [link](https://drive.google.com/file/d/1JUQgtIhXiPc-hAv7Fr6eu3No66VpyayM/view?usp=sharing) has some error. The page is not found for me. Please check it.

Regards,
Sungguk Cha

**Comment by younesbelkada** [comment]
Hi Sungguk!

First of all Happy new year!
Thank you so much for your message and for the interest in our work. I am very sorry for the late reply. In order to download the LOOK dataset and ground truth annotations, please carefully follow the instructions on the [LOOK Dataset web page](https://looking-vita-epfl.github.io/dataset/). The README file has been modified accordingly
Please let me know if anything else is missing

Best regards
